const projects = [
  {
    Id: 0,
    Slug: 'artifact-holiday-memory',
    Title: 'Artifact Digital Holiday Card',
    Thumbnail: 'memory.png',
    Thumbnail_caption: 'Experience',
    Images: ['/mbp-artifact1.png', '/ipad-artifact.png'],
    Text: [
      'While working as an intern at Artifact Design in Atlanta, I developed their anual holiday card. The designers and animators came up with a "memory game" concept where an animation would fire whenever you get a match.',
      'This is my first project I worked on that was deployed live to the web. I love looking back at how ambitious I was coming out of school.',
    ],
    A11y: 'Screenshots of Holiday Memory game',
    Link: 'http://dev.herbtorres.com/artifact-holiday/',
  },
  {
    Id: 1,
    Slug: 'learn-with-youtube',
    Title: 'YouTube Learning',
    Thumbnail: 'logo-rewind-16.png',
    Thumbnail_caption: 'Website',
    Images: ['/preview-ats.jpg', '/preview-kaiya-start.png'],
    Text: ['YouTube #learnwithme copy', 'Text line two!'],
    A11y: 'Screenshots of YouTube Learning site',
    Link: 'https://learnathome.withyoutube.com/',
  },
  {
    Id: 2,
    Slug: 'google-news',
    Title: 'Google News',
    Thumbnail: 'logo-news.png',
    Thumbnail_caption: 'Marketing site',
    Images: ['/mbp-news.png', '/imac-news.png'],
    Text: [
      'This marketing site is for Google News, an app developed by Google that presents a continuous, customizable flow of articles organized from thousands of publishers and magazines.',
      'This site was localized for 8 different languages and is built using Google’s internal tools and frameworks.',
    ],
    A11y: 'Screenshots of Google News marketing site',
    Link: 'https://news.google.com/about/',
  },
  {
    Id: 3,
    Slug: 'canvas-hangouts',
    Title: 'Google Hangouts',
    Thumbnail: 'logo-hangouts-canvas.png',
    Thumbnail_caption: 'Marketing site',
    Images: ['/mbp-canvas.png', '/imac-canvas.png'],
    Text: [
      'Google Hangouts Meet had a special campaign where they featured various artist’s work as selectable backgrounds in Google Hangouts.',
      'This site is built using Google’s internal tools and frameworks.',
    ],
    A11y: 'Screenshots of Hangouts with Google site',
    Link: 'https://canvasproject.withgoogle.com/',
  },
  {
    Id: 4,
    Slug: 'smallthanks',
    Title: '#SmallThanks with Google',
    Thumbnail: 'logo-smallthanks.png',
    Thumbnail_caption: 'Marketing site',
    Images: ['/mbp-smallthanks.png', '/imac-canvas.png'],
    Text: [
      '#SmallThanks with Google is a marketing campaign to showcase some new Google Map features. This new tool utilizes existing customer Google reviews and highlights your best Google reviews by automatically creating a poster that you can print for your business, send in an email campaign, or even feature on your website.',
      'This site has some dynamic content that loads depending on where you’re viewing the site. There’s a parameter you can add to view these by adding ?city=lou to the URL. nyc, dal and indy are among a few others.',
    ],
    A11y: 'Screenshots of Hangouts with Google site',
    Link: 'https://canvasproject.withgoogle.com/',
  },
  {
    Id: 5,
    Slug: 'touch-of-sweetness',
    Title: 'A Touch of Sweetness',
    Thumbnail: 'logo-ats.png',
    Thumbnail_caption: 'Marketing site',
    Images: ['/mbp-ats1.png', '/mbp-ats2.png'],
    Text: [
      'This website is for a pastry chef’s company called A Touch Of Sweetness. A specialty made-to-order pastry service based in Ann Arbor, Michigan.',
      'Built using Vue.js',
    ],
    A11y: 'Screenshots of A Touch of Sweetness site',
    Link: 'http://www.a2touchofsweetness.com/',
  },
  {
    Id: 6,
    Slug: 'lighthouse-jobs',
    Title: 'Harbor Jobs',
    Thumbnail: 'sub.png',
    Thumbnail_caption: 'Job Search site',
    Images: ['/mbp-ats1.png', '/mbp-ats2.png'],
    Text: ['Talk about the Harbor Jobs site...', 'Wordpress customizations'],
    A11y: 'Screenshots of Lighthouse Jobs site',
    Link: 'http://www.a2touchofsweetness.com/',
  },
  {
    Id: 7,
    Slug: 'kraft-starwars',
    Title: 'Kraft Mac N’ Cheese',
    Thumbnail: 'logo-starwars.png',
    Thumbnail_caption: 'Experience',
    Images: ['/mbp-starwars1.png', '/mbp-starwars2.png'],
    Text: [
      'Kraft Mac N Cheese teamed up with Star Wars to make Star Wars shaped pasta shells for the new The Force Awakens movie. This site lets the user navigate through a Star Wars memorabilia museum to tap into that Star Wars nostalgia.',
      'Built using Backbone.js',
    ],
    A11y: 'Screenshots of Kraft StarWars site',
    Link: 'http://dev.herbtorres.com/kraft-star-wars/',
  },
  {
    Id: 8,
    Slug: 'banner-ads',
    Title: 'HTML5 Banners',
    Thumbnail: 'badge.png',
    Thumbnail_caption: 'Banner ads',
    Images: ['/mbp-starwars1.png', '/mbp-starwars2.png'],
    Text: ['2021 HTML5 banner rhettoric', 'More rehotoric'],
    A11y: 'Screenshots of Kraft StarWars site',
    Link: 'http://dev.herbtorres.com/kraft-star-wars/',
  },
];

export default projects as any;
